[package]
name = "na_rust"
version = "1.0.4"
edition = "2021"
description = "A command line tool for adding and listing project todos (Rust rewrite of na)"
license = "MIT"
authors = ["Brett Terpstra <me@brettterpstra.com>"]
homepage = "https://brettterpstra.com/projects/na/"
repository = "https://github.com/ttscoff/na_rust"

[[bin]]
name = "na"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.95"
chrono = { version = "0.4.39", features = ["clock", "serde"] }
clap = { version = "=4.4.18", features = ["derive"] }
inquire = "0.9.4"
interim = { version = "0.2", features = ["chrono_0_4"] }
regex = "1.11.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
serde_yaml = "0.9.34"
walkdir = "2.5.0"
